spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_goods?characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: root

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.cloud.goods.entity
  
feign:
  hystrix:
    enabled: true